### ISSUE TITLE
Adding images or Font Awesome icons

### ISSUE THREAD

**Issue by kgfox1** [ulrichwisser/MMM-HTMLSnippet#2]
I am trying to make a row of icons in the HTML Snippet but it does not load images that I have placed in the Pictures folder of the Raspberry pi, nor can I seem to figure out how to code in use of Font Awesome.  Any help is appreciated!

**Comment by ulrichwisser** [comment]
Can you view the images in a different tab of your browser? If so, please copy the full URL into the HTML source of  your snippet. 
The snippet is loaded as an iframe. You should really include a full HTML page in the snippet. Fonts can be included as in any other page. 
please send an email if this doesn't help.
