### ISSUE TITLE
Fail to display module

### ISSUE THREAD

**Issue by mrfoxie** [ulrichwisser/MMM-HTMLSnippet#4]
I tried to install it but I got this error while exciting it. Check the screenshot
![Screenshot from 2022-04-25 17-20-09](https://user-images.githubusercontent.com/25217451/165083424-8029fea3-4a23-4818-807c-858889396693.png)

also here is the code I used from the documentation.
```js
{
            module: "MMM-HTMLSnippet",
            position: "top_left",
            config: {
                html: `<h1>Test</h1>`, //insert your script or html codes here.
                width: "600px",
                height: "300px",
                backgroundColor: "#FFF",
                updateInterval: 3600000,
            }
        },
```

![Screenshot from 2022-04-25 17-21-17](https://user-images.githubusercontent.com/25217451/165083557-da82e010-895a-4940-b077-a8f4b8cebb45.png)

**Comment by ulrichwisser** [comment]
You didn't say, but I guess you followed the instructions and installed MMM-HTML-Snippet?
Could you have a look at the logs when you start MM?
What version of MM are you using? And on which OS and NPM?

**Comment by mrfoxie** [comment]
I reinstall it using documentation and gave it a hard restart and it worked thank you.

**Comment by ulrichwisser** [comment]
I hardly did anything. Glad it worked out for you!
