### ISSUE TITLE
Display several IFrame on Magic Mirror

### ISSUE THREAD

**Issue by swatchpeter** [ulrichwisser/MMM-HTMLSnippet#5]
Hello
Thanks for your very efficient module.
Is it possible to have several Iframe displayed with your module ?
Is it possible to call your module several times in the config.js?

Thanks for your help
Best Regards

**Comment by ulrichwisser** [comment]
Thank you for using the module!
The module is very simple, it just wraps your html in an iframe. So there is no possibility to have several iframes in the module. 
On the other hand, it should be no problem to use the module several times in your config.js. 
I hope this helps. Please let me know if there are any problems.
Greetings from sunny Sweden
/Ulrich

**Comment by swatchpeter** [comment]
Thanks for your answer.
Just a last question ; if i use several times the module in my config.js, can i use display different URL ?
Greetings from sunny South of France ;-)
Peter

**Comment by swatchpeter** [comment]
Thanks a lot, i'm going to try that.
Excellent !

**Comment by swatchpeter** [comment]
Hello Ulrich,
I've tryed it and it's not working....
I'm displaying graph from my grafana server....
Can you help me ?
Thanks in advance

Here is my config.js and a snapshot


		{
			module: "MMM-HTMLSnippet",
			header: "Garden",
			disabled: false,
			position: "top_left",
			config: {
			  html:`<iframe src="http://piportailstats:3000/d-solo/aQs6_OZRz/meteo_db?orgId=1&panelId=2&theme=dark" width="450" height="200" frameborder="0"></iframe>`, //insert your script or html codes here.
			  width: "450px",
			  height: "200px",
			  backgroundColor: "#000",
			  updateInterval: 600000,
			}
		},
		{
			module: "MMM-HTMLSnippet",
			header: "Pool",
			disabled: false,
			position: "top_right",
			config: {
			  html:`<iframe src="http://piportailstats:3000/d-solo/Ryzdh8Zgk/test2?orgId=1&theme=dark&panelId=4" width="450" height="200" frameborder="0"></iframe>`, //insert your script or html codes here.
			  width: "450px",
			  height: "200px",
			  backgroundColor: "#000",
			  updateInterval: 600000,
			}
		},
![2022-05-24 10-54-25](https://user-images.githubusercontent.com/26225863/169992157-768880ab-28af-4a76-a3ad-917896ff044b.png)

**Comment by ulrichwisser** [comment]
This seems to be an error in the module. Give me a few hours to fix.

**Comment by swatchpeter** [comment]
Hello
It's very Strange, it's the opposite : I have the 2nd url everywhere.

I'm going to try it with external links.
Best Regards
![2022-05-24 16-11-27](https://user-images.githubusercontent.com/26225863/170056477-03ee44a7-77ad-4732-8813-641fcb9eb5ef.png)

**Comment by ulrichwisser** [comment]
Did you use a different ident for each instance?
If you move the mouse over the iframe and then do a right click and chose ""open frame i new window" you should get a new window this the address ending in HTMLSNIPPET-<ident>

**Comment by ulrichwisser** [comment]
Please insert idents in your config something like 

```
{
		module: "MMM-HTMLSnippet",
		header: "Garden",
                disabled: false,
		position: "top_left",
		config: {
		  html:'<iframe id="widget_autocomplete_preview"  width="150" height="300" frameborder="0" src="https://meteofrance.com/widget/prevision/341720"> </iframe>', //insert your script or html codes here.
		  width: "450px",
		  height: "200px",
		  backgroundColor: "#000",
		  updateInterval: 600000,
                  ident: "weather1",
		}
	},
	{
		module: "MMM-HTMLSnippet",
		header: "Pool",
		disabled: false,
		position: "top_right",
		config: {
		  html:'<iframe id="widget_autocomplete_preview"  width="150" height="300" frameborder="0" src="https://meteofrance.com/widget/prevision/751010"> </iframe>', //insert your script or html codes here.
		  width: "450px",
		  height: "200px",
		  backgroundColor: "#000",
		  updateInterval: 600000,
                  ident: "weather2",

		}
	},
```

**Comment by swatchpeter** [comment]
Yeeeessss !!!!
It's working !
Thanks a lot !
