### ISSUE TITLE
mjpeg video refreshinterval

### ISSUE THREAD

**Issue by costascontis** [ulrichwisser/MMM-HTMLSnippet#6]
i and using this nice module to display my door's camera to my mirror and it works just fine.My question is ,can i use the module displaying my camera link without refreshing it ?I could have set the refreshinterval to something big like 1800000(30 mins).The problem is that when mirror starts its not showing the feed right away but waits the first refresh to show it....Can i do something about it?
Thnx

**Comment by ulrichwisser** [comment]
Thanks for using the module!

The first display should always happen 2 seconds after start. 
Any further updates are scheduled with the configuration value. Have you tried to configure it to -1?
(Currently I am traveling and have no access to my mirror otherwise I would try it myself.)

**Comment by costascontis** [comment]
> The first display should always happen 2 seconds after start.
i changed the 2 secs to 10 seconds and now starts fine.Can i disable the updateinternal somehow?

**Comment by ulrichwisser** [comment]
I know, it took me a long time, sorry for that! Now updateinterval=0 will stop doing updates.
