### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by jimmyhartington** [ulrichwisser/MMM-HTMLSnippet#8]
I used the old version.

Recently updated to the new version. Adjusted the configuration.

But now the snippets does not refresh at all.

**Comment by ulrichwisser** [comment]
Hi Jimmy,
thanks for using the module! 
I have run a few tests here and it updates for me. That is of course not saying much.
So lets check a few things on your install.
- Do you have one snippet or several?
-  Is updateInterval set to a non zero value

**Comment by jimmyhartington** [comment]
It is a good module.

Here is my config.
`
 {
		module: "MMM-HTMLSnippet",
		position: "top_left",
		config: {
		  width: "600px",
		  height: "830px",
		  backgroundColor: "#000",
		  color: "#000",
		  updateInterval: 300000, // in milli seconds
		  ident: "madplan",
		  frames: [
			{
			  html:`<iframe src="https://docs.google.com/PRIVATESPREADSHEET/pubhtml?single=true&gid=0&range=A1:e10&widget=false&chrome=false"  width="95%" height="95%"  scrolling="no" frameBorder="0"></iframe><img style="top:0px; left:0px; position:absolute; z-index:9" src="http://10.10.10.20:880/magicmirror/overlay.png">`,
			}
		  ]
		}
	  },

	  {
		module: "MMM-HTMLSnippet",
		position: "bottom",
		config: {
		  width: "960px",
		  height: "500px",
		  backgroundColor: "#EAF7F7",
		  ident: "elpriser",
		  updateInterval: 300000,
		  frames: [
			{
			  html:`<script src="https://www.elprisenligenu.dk/api/v1/iframeResizer.min.js"></script><iframe title="Elpriser fra elprisenligenu.dk" src="https://www.elprisenligenu.dk/i/aarhus?mode=embed&layout=minimal&hide-examples=1&zoom=1.2" style="width:100%;height:500px;border:0;" onload="iFrameResize({heightCalculationMethod: 'taggedElement', checkOrigin: false}, this);"></iframe>`,
			}
		  ]
		},
	  }
`

It worked with one snippet with the old version.

**Comment by oturan233** [comment]
Thanks for this great module, same for me, it is not working after update. "Loading connections" on the screen.

**Comment by ulrichwisser** [comment]
Seems I have over optimized my source code. 
I just checked in a small change. Could you please try and see if it fixes the problem for you?

**Comment by jimmyhartington** [comment]
Thanks. This solved my issue. It is now updating at the intervals defined in the config file.

**Comment by ulrichwisser** [comment]
@oturan233 hope it solved your problem too. 
Thanks Jimmy for reporting the problem.

**Comment by ulrichwisser** [comment]
Hi @oturan233, please open a new issue and share your config.
